name: insurance-risk-ml
channels:
  - conda-forge
dependencies:
  - python=3.10  
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - optuna
  - shap
  - streamlit
  - pyarrow
  - jupyterlab
  - ipykernel
  - pip
  - category_encoders
  - gunicorn
  - pip:
      - pre-commit
